blog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('articles/', include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name= "Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name= "comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

blog/article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]
        

blog/article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(content__contains = keyword)
        return render(request,"articles.html",{"articles":articles})

    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"<b>" + str(article) + "</b> isimli makale başarıyla oluşturuldu!",extra_tags="safe")
        return redirect("index")
    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance= article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"<b>" + str(article) + "</b> isimli makale başarıyla güncellendi!",extra_tags="safe")
        return redirect("index")

    return render(request,"update.html",{"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    deleted_article = str(article)
    article.delete()
    messages.info(request,"<b>" + deleted_article + "</b> isimli makale başarıyla silindi!",extra_tags="safe")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()

        messages.success(request,"Yorumunuz başarıyla iletildi, teşekkür ederiz! " + "<b>" + str(comment_author) + "</b>",extra_tags="safe")

    return redirect(reverse("article:detail",kwargs={"id":id}))

blog/templates/about.html
{% extends "layout.html" %}

{% block body %}
<div class="col-md-7 offset-md-3">
    <h5>
        Hakkımda
    </h5>
    <hr>
        Herkese merhaba!Burası hakkımda bilgilerin yer aldığı sayfadır.
</div>
{% endblock  %}

blog/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
<div class="col-md-6 offset-md-3">
<h5>Makale Oluştur</h5>
<hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Makale Ekle</button>
</form>

</div>
</div>

{% endblock  %}

blog/templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
        <h5>
            Makaleler
        </h5>
        <hr>
    </div>
</div>
<div class = "row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                {% csrf_token %}
                <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara...">
                <button type="submit" class="btn btn-danger">Ara</button>
            </form>   
        </div>    
    </div>
</div>
     
{% if articles %}
{% for article in articles %}
    <div class="row">
        <div class="col-md-10 offset-md-3">
        
            <!-- Post Content Column -->
            <div class="col-lg-8">

                <!-- Title -->
                <a href="{% url 'article:detail' article.id %}">
                    <h2 class="mt-4">{{article.title}}</h2>
                </a>

                <!-- Author -->
                <p class="lead">{{article.author.username}} tarafından yayınlandı</p>              
                <hr>

                <!-- Date/Time -->
                <p>{{article.created_date}} / Tarihinde oluşturuldu.</p>
                <hr>

                <!-- Preview Image -->
                {% if article.article_image %}
                <a href="{% url 'article:detail' article.id %}">
                    <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                </a>
                {% endif %}
                <hr>

                <!-- Post Content -->
                <p class="lead">
                    {{article.content|safe|truncatewords:20}}
                
                <a style = "float : right;" href="{% url 'article:detail' article.id %}">Devamını Oku</a>
                </p>
                <hr>

                <!-- Sidebar Widgets Column -->
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% else %}
<br>
<div class="col-md-7 offset-md-3">
    <div class = "alert alert-danger">
        Makale bulunamadı.
    </div>
</div>
{% endif %}

{% endblock  %}

blog/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<div class="col-md-7 offset-md-3">
    <h5>Kontrol Paneli</h5>
    <hr>
    <p>
        Hoşgeldiniz, <small>{{request.user.username}}</small>
    </p>
    <hr>
    <a href="/articles/addarticle" class="btn btn-danger">Makale Ekle</a>
    <br><br>

{% if articles %}
    <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col"></th>
            <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-warning">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}
        <tr>
        </tbody>
    </table>
</div>
{% else %}
<div class="col-md-7 offset-md-3">
    <div class="alert alert-danger">
        Henüz bir makaleniz bulunmuyor...
    </div>
</div>
{% endif %}


{% endblock  %}

blog/templates/detail.html
{% extends "layout.html" %}

{% block body %}

    <div class="row">
      <div class="col-md-7 offset-md-3">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h2 class="mt-4">{{article.title}}</h2>

          <!-- Author -->
          <p class="lead">
            {{article.author.username}} tarafından yayınlandı
          </p>

          <hr>

          <!-- Date/Time -->
          <p>{{article.created_date}} / Tarihinde oluşturuldu.</p>

          <hr>

          <!-- Preview Image -->
          {% if article.article_image %}
          <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
          {% endif %}
          

          <hr>

          <!-- Post Content -->
          <p class="lead">
              {{article.content|safe}}
          <p>

          <hr>

          <!-- Comments Form -->
          <h5>Yorumlar</h5>
          <hr>
          {% if comments %}
          {% for comment in comments %}
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.comment_author}}</h5>
                {{comment.comment_date}}
                <br>
                {{comment.comment_content}}
            </div>
          </div>          
          {% endfor %}
          {% else %}
          <div class = "alert alert-danger">
            Bu makaleye herhangi bir yorum yazılmamıştır. İlk yorumu yapan siz olun!
          </div>
          {% endif %}
          <div class="card my-4">
            <h5 class="card-header">Yorum gönderin:</h5>
            <div class="card-body">
              <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
                <div class="form-group">
                  <label for="formGroupExampleInput">İsminiz</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi giriniz...">
                </div>
                <div class="form-group">
                  <label for="formGroupExampleInput">Yorumunuz</label>
                  <textarea name = "comment_content" class="form-control" rows="3" placeholder = "Yorumunuzu giriniz..."></textarea>
                </div>
                <button type="submit" class="btn btn-danger">Gönder</button>
              </form>
            </div>
          </div>


          <!-- Sidebar Widgets Column -->
          <div class="col-md-4">






          </div>
        </div>
      </div>
    </div>

{% endblock  %}

blog/templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="col-md-7 offset-md-3">
    <div class = "jumbotron text-center">
        <h3>Blog Sayfasına Hoşgeldiniz</h3>
        <p>
            Bu blogta gönüllü olarak kendi yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.
        </p>
    </div>
</div>
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Atılım Koçak</title>
</head>
<body>
        {% include "includes/navbar.html" %}

        <div style = "margin-top: 60px; margin-bottom: 60px;" class = "container">
            <div class="col-md-7 offset-md-3">
                {% if messages %}
                    {% for message in messages %}
                    {% if message.level_tag == "info" %}
                        <div class="alert alert-danger">{{ message|safe }}</div>
                    {% else %}
                        <div class="alert alert-{{ message.level_tag }}">{{ message|safe }}</div>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        {% block body %}
        
        {% endblock  %}
        
        </div>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!--<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>-->
        <script src="{% static 'js/run_prettify.js' %}"></script>

</body>
</html>

blog/templates/login.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}



<div class="row">
<div class="col-md-6 offset-md-3">
<h5>Giriş Yap</h5>
<hr>
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Giriş Yap</button>
</form>

</div>
</div>

{% endblock  %}

blog/templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<div class="row">
<div class="col-md-6 offset-md-3">
<h5>Kayıt Ol</h5>
<hr>
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Kayıt Ol</button>
</form>

</div>
</div>
{% endblock  %}

blog/templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
<div class="col-md-6 offset-md-3">
<h5>Makaleyi Güncelle</h5>
<hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-warning">Güncelle</button>
</form>

</div>
</div>

{% endblock  %}